# Generated by Django 3.1.7 on 2021-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_auto_20210720_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
