# Generated by Django 3.1.7 on 2021-07-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_auto_20210720_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slugField',
            field=models.SlugField(default=''),
        ),
    ]
