# Generated by Django 3.1.7 on 2021-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_books_slugfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='extra',
            field=models.IntegerField(default=0),
        ),
    ]
