# Generated by Django 3.1.7 on 2021-07-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_books_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='extra',
        ),
    ]
