# Generated by Django 3.1.7 on 2021-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_auto_20210721_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bookCount',
            field=models.IntegerField(default=0),
        ),
    ]
